### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [wbenbihi/hourglasstensorlfow#10]
Can you please share the pretrained model ?

**Comment by wbenbihi** [comment]
You can find pretrained models on the READ ME file.
https://drive.google.com/open?id=0B03jF2Gc59lRbUJXWEpnc2dWemM to download a version with 80 Convolutional Layers. You don't need the *.meta file to generate the graph. The code should load the right weights if you used the config.cfg correctly.

**Comment by 13185742215** [comment]
master，the link has broken.
Could you please re-share the model?
Thank you very much!!
