### ISSUE TITLE
Issue: missing meta file. 

### ISSUE THREAD

**Issue by AlonTetro** [wbenbihi/hourglasstensorlfow#12]
First of all, 
Thanks :)))) 

I have a little problem.
When I downloaded the pre-train model file I can't found the hourglass_bn_100.meta file,
So how can I restore the model ? 

Thanks a lot :)

**Comment by wbenbihi** [comment]
The meta file is too big. You do not need it to restore the model, check the predictClass.py file. By running it with the good config.cfg file you will be able to restore the pretrained model. 
Next commit should be available on September, Friday 8th
