### ISSUE TITLE
a suggestion in _hourglass() function

### ISSUE THREAD

**Issue by GodsDusk** [wbenbihi/hourglasstensorlfow#14]
I think
up_2 = tf.image.resize_nearest_neighbor(low_3, tf.shape(low_3)[1:3]*2, name = 'upsampling')

should be 

up_2 = tf.image.resize_nearest_neighbor(low_3, tf.shape(up_1)[1:3], name = 'upsampling')

so it could handle those input size is not 2^n

**Comment by wbenbihi** [comment]
You are right. Thank you for your update I will modify this.

**Comment by LucasMahieu** [comment]
This could be replace by : `up_2 = tf.image.resize_nearest_neighbor(low_3, [(2**(n+1))*2, (2**(n+1))*2], name = 'upsampling')`
