### ISSUE TITLE
High accuracy with incorrect result

### ISSUE THREAD

**Issue by o0t1ng0o** [wbenbihi/hourglasstensorlfow#16]
Hi~
@wbenbihi 
I have tried to train my own model with my dataset. Although the accuracy is about 87.6% after the fourth epoch, the result of  valid image is totally incorrect. My training set is about 400K, and my valid set is about 40K. I am really confused. 
By the way, the *.meta file cannot be found from the link you offered. Only the *.index and *.data-00000-of-00001 files can be found. So i trained my model without any pretained model..

My training log :
 Train: ====================>>||100.% -cost: 692.13 -avg_loss: 0.027 -timeToEnd: 0 sec.Epoch 0/200 done in 26694 sec. -avg_time/batch: 1.05 sec.
('--Avg. Accuracy =', '86.591', '%')
Epoch :1/200

 Train: ====================>>||100.% -cost: 279.80 -avg_loss: 0.011 -timeToEnd: 0 sec.Epoch 1/200 done in 26478 sec. -avg_time/batch: 1.04 sec.
('--Avg. Accuracy =', '87.437', '%')
Epoch :2/200

 Train: ====================>>||100.% -cost: 273.10 -avg_loss: 0.010 -timeToEnd: 0 sec.Epoch 2/200 done in 26285 sec. -avg_time/batch: 1.04 sec.
('--Avg. Accuracy =', '87.116', '%')
Epoch :3/200

 Train: ====================>>||100.% -cost: 270.24 -avg_loss: 0.010 -timeToEnd: 0 sec.Epoch 3/200 done in 26145 sec. -avg_time/batch: 1.03 sec.
('--Avg. Accuracy =', '87.079', '%')
Epoch :4/200

 Train: ====================>>||100.% -cost: 268.74 -avg_loss: 0.010 -timeToEnd: 0 sec.Epoch 4/200 done in 26106 sec. -avg_time/batch: 1.03 sec.
('--Avg. Accuracy =', '87.679', '%')
Epoch :5/200

Here is the link of my checkpoints, the code to predict the image and a part of valid set.
http://pan.baidu.com/s/1mieNxzU

Could u please check out the reason for me?

**Comment by dongzhuoyao** [comment]
It seemed that the accuracy is calculated in training set???

```
self.valid_gen = self.dataset._aux_generator(self.batchSize, self.nStack, normalize = True, sample_set = 'valid')
```
is of no use

@wbenbihi
