### ISSUE TITLE
How to display result 

### ISSUE THREAD

**Issue by Crazod** [wbenbihi/hourglasstensorlfow#17]
Hi I use this code in inference.py to detect human estimation
```
from inference import Inference
a = Inference()
a.webcamSingle()
```
but it seems  that there are no results. I have used different pretained model .
Can you give me an example how to use the inference.py?

I have also try the webcamYOLO and get the right results

**Comment by beckyng2194** [comment]
@Crazod Are you able to show me code you used to try webcamYOLO?

**Comment by Crazod** [comment]
HI 
@beckyng2194 I add code at inference.py
`if __name__ == '__main__':
	params = process_config('config.cfg')
	dataset = DataGenerator(params['joint_list'], params['img_directory'], params['training_txt_file'], remove_joints=params['remove_joints'])
	infer = Inference()
	infer.webcamSingle()
`
webcamYOLO is similiar
