### ISSUE TITLE
Net Structure

### ISSUE THREAD

**Issue by Turlan** [wbenbihi/hourglasstensorlfow#20]
Can you visualize the net structure? 
I hope you can provide the figure of the net structure.
That will very helpful for me to understand the net. Thank you.

**Comment by williamdwl** [comment]
![image](https://user-images.githubusercontent.com/26170993/50446729-71566880-0951-11e9-8ba2-ae9f4d7bcb9d.png)

**Comment by williamdwl** [comment]
![image](https://user-images.githubusercontent.com/26170993/50446743-8df2a080-0951-11e9-93f2-bc6b9ff1904e.png)

**Comment by xiaoxin05** [comment]
hi ,can you send to me with a network's structure
