### ISSUE TITLE
Run program using CPU

### ISSUE THREAD

**Issue by albertchristianto** [wbenbihi/hourglasstensorlfow#25]
greetings,
I am interested with this project, but I am newbie on tensorflow and I don't GPU support to run on tensorflow-GPU. I can see that there is a code for CPU device, but I have hard time to modify it. is there anyone can help me with it ? At least give me some hint or suggestion to modify the code?
Thank you.
best regards,
Albert

**Comment by kyrsaexp** [comment]
I guess you can just replace self.gpu in HourglassModel from '/gpu:0' to '/cpu:0'

**Comment by albertchristianto** [comment]
@usernameis666 really, man. It's work. 
Haha thanks a lot. I guess this is a silly question.
