### ISSUE TITLE
Difference between RegularHG mode and TinyHG model

### ISSUE THREAD

**Issue by FightForCS** [wbenbihi/hourglasstensorlfow#27]
Hi, thanks for your work. I want to know the difference between RegularHG model and TinyHG model? Why TinyHG model is larger?
I notice that those two pre-trained models have the same 'config.cfg' file, does it mean that they are the same model? Is there something that I am missing?
I have checked the original paper, actually I did not found a clue about 'tiny'. Hoping someone can help me. Thanks a lot.

**Comment by weiyx16** [comment]
You can check the network structure in detail and they are different in the structure, especially in the definition of the residual block. In fact the regular one is what mentioned in the original paper, but tiny one also works well.  
You can find some difference in hourglass_tiny.py like here:  
``
if self.tiny:  
     with tf.name_scope(name):  
           norm = tf.contrib.layers.batch_norm(inputs, 0.9, epsilon=1e-5, activation_fn = tf.nn.relu, is_training = self.training)  
           pad = tf.pad(norm, np.array([[0,0],[0,0],[1,1],[1,1]]), name= 'pad')  
           conv = self._conv(pad, int(numOut), kernel_size=3, strides=1, name= 'conv')  			
           return conv  
``
