### ISSUE TITLE
Can I fine tune from pre-trained model?

### ISSUE THREAD

**Issue by FightForCS** [wbenbihi/hourglasstensorlfow#28]
Can I restore from pre-trained model and fine tune on another task? Say I want to detect 10 types of key points, how can I modify the code? Since directly loading the original model parameter will give 'dimension not match' error(MPII has 16 key points). Thanks.

**Comment by lmhlll** [comment]
I want to fine tune from pre-trained model ,too.
Have you resolved it ?
