### ISSUE TITLE
Organize a tf_record dataset

### ISSUE THREAD

**Issue by bhack** [wbenbihi/hourglasstensorlfow#3]
What do you think of using a [dataset fromat](https://www.tensorflow.org/api_docs/python/tf/contrib/data/TFRecordDataset)?
This is an example for the [Mscoco object detection](https://github.com/MetaPeak/tensorflow_object_detection_create_coco_tfrecord) but could be also very similar for keypoints

**Comment by bhack** [comment]
Another example https://github.com/visipedia/tfrecords

**Comment by wbenbihi** [comment]
Thank you,
I  already started to look into protocol buffer to make better preprocessing. I currently use .txt file to make it easier to train the model on different dataset.

**Comment by bhack** [comment]
Yes I undestrand but probably a tfrecords generator like this one could be quite easy to adapt on different dataset to have an unique input format.
