### ISSUE TITLE
Typo in hourglass_tiny.py?

### ISSUE THREAD

**Issue by sungheonpark** [wbenbihi/hourglasstensorlfow#30]
Hi, thanks for sharing the code. It helps a lot for my research.
BTW, I think there's a typo in the model definition. In line 472 of hourglass_tiny.py
sum_[i] = tf.add_n([out_[i], sum_[i-1], ll_[0]], name= 'merge')
I think ll_[0] should be fixed to ll_[i]. This might be critical for the performance..

**Comment by wenmingMeng** [comment]
It makes me confused too, looking forward to author's reply !

**Comment by LucasMahieu** [comment]
any feedabck about this ?
