### ISSUE TITLE
heatmap resize to other size

### ISSUE THREAD

**Issue by watlz1533** [wbenbihi/hourglasstensorlfow#36]
I have a image (1024x768), first convert the image to 256x256, then execute predictHM(img) and get a 64x64 heat map.
In inference.py, the function predictHM(self, img) returns 64x64 heat map.
Can any function convert the heat map to original image size (ex: 1024x768)?

**Comment by xuebuaa** [comment]
have you sloved this problem？the resolution of the output heatmap is too low ,could i change the upsampling structure to improve the resolution?
