### ISSUE TITLE
What use of YOLO_small.ckpt ???

### ISSUE THREAD

**Issue by Sunshine352** [wbenbihi/hourglasstensorlfow#37]
def __init__(self, config_file = 'config.cfg', model = 'hg_refined_tiny_200', yoloModel = 'YOLO_small.ckpt'):
		""" Initilize the Predictor
		Args:
			config_file 	 	: *.cfg file with model's parameters
			model 	 	 	 	: *.index file's name. (weights to load) 
			yoloModel 	 	: *.ckpt file (YOLO weights to load)
		"""
		t = time()
		params = process_config(config_file)
		self.predict = PredictProcessor(params)
		self.predict.color_palette()
		self.predict.LINKS_JOINTS()
	        **self.predict.model_init()
		self.predict.load_model(load = model)
		self.predict.yolo_init()
		self.predict.restore_yolo(load = yoloModel)**
		self.predict._create_prediction_tensor()
		self.filter = VideoFilters()
		print('Done: ', time() - t, ' sec.')

**## self-trained model->'hg_refined_tiny_200',  Why to overwrite with 'YOLO_small.ckpt' model ?**

**Comment by xuhw16** [comment]
I am also confused,have you figure out why  to overwrite with 'YOLO_small.ckpt' model ?
