### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by sirykd** [wbenbihi/hourglasstensorlfow#4]
Hi! It would be great if you could share a pretrained model, which people would be able to run and get the results without spending 2+ days on training.

**Comment by wbenbihi** [comment]
Hi,
You can download a pretrained model [here](https://drive.google.com/file/d/0B03jF2Gc59lRX0ZjbFJLaWZUSUk/view?usp=sharing) 
Tell me If you have any trouble, some tools should be available soon for prediction and visualization.

**Comment by bhack** [comment]
@wbenbihi Seems that you have inferencing and visualization scripts. I'm modifying _train for doing inference but if you have it quite ready could be an useful base.

**Comment by bhack** [comment]
Is there not too much duplicated/overlapping code now between hourglass_tiny and hourglass_tiny_testing?

**Comment by wbenbihi** [comment]
hourglass_tiny_testing is a backup file. You cannot use the new hourglass_tiny with the pretrained model and it is not compatible with the predictClass.py. I am making a cleaner code. Should be available at the end of the week.

**Comment by bhack** [comment]
Yes I'have seen this.. but was just a feedback about how the code was organized between this two files.

**Comment by bhack** [comment]
There are missing Yolo python imports.. Another alternative is to use one of the models zoo available in TF new [Object detection API](https://github.com/tensorflow/models/blob/master/object_detection/)

**Comment by bhack** [comment]
Now yolo code is imported in the repository but you are mixing your code under MIT with unkown yolo code license. [This version](https://github.com/hizhangp/yolo_tensorflow) is under the same of your code but I've not test it. Probably could better to separate in two files the code that requires a detector form the code that doesn't require one (I.e. single person methods etc.)

**Comment by o0t1ng0o** [comment]
Hi~
@wbenbihi 
There are only two files about the pretrained model.
(hourglass_bn_100.data-00000-of-00001
hourglass_bn_100.index)

But, when i restore the your pretrained model, i need the file suffixed by ".meta".

Could you please offer this file?

**Comment by cardcaster** [comment]
Hi,
I'm new to tensorflow and I'm trying to use the pretrained model called Regular Hourglass (80 Convolution layer) (ref/refined_tiny). I read the readme.txt and as instructed I edited hourglass_tiny.py and changed 
`def restore(self, load = None):` 

 to

`def restore(self, load = 'saver_directory'):`

My config.cfg file looks like this
```
[DataSetHG]
training_txt_file: 'dataset.txt'
img_directory: '/Users/cardcaster/Downloads/hourglasstensorlfow-master/images/'
img_size: 256
hm_size: 64
num_joints: 16
remove_joints: None
joint_list = ['r_anckle', 'r_knee', 'r_hip', 'l_hip', 'l_knee', 'l_anckle', 'pelvis', 'thorax', 'neck', 'head', 'r_wrist', 'r_elbow', 'r_shoulder', 'l_shoulder', 'l_elbow', 'l_wrist']`
[Network]
name: 'hg_refined'
nFeats: 256
nStacks: 4
nModules: 1
tiny: False
nLow: 4
dropout_rate: 0.2
mcam: False
[Train]
batch_size: 4
nEpochs: 200
epoch_size: 1000
learning_rate: 0.00025
learning_rate_decay: 0.96
decay_step: 2000
weighted_loss: False
[Validation]
valid_iteration: 10
[Saver]
log_dir_train: 'F:/Cours/DHPE/DHPE/hourglass_tiny/'
log_dir_test: 'F:/Cours/DHPE/DHPE/hourglass_tiny/'
saver_step: 500
saver_directory: '/Users/cardcaster/Downloads/hourglasstensorlfow-master/pretrained-model/'
```


However, as mentioned in the readme.txt I should use the same config file but the pretrained model comes with its own config.cfg file. Which one should I be using?

Thank you.

**Comment by Ziang-Wang** [comment]
> 嗨，
> 您可以[在这里](https://drive.google.com/file/d/0B03jF2Gc59lRX0ZjbFJLaWZUSUk/view?usp=sharing)下载经过训练的模型[。](https://drive.google.com/file/d/0B03jF2Gc59lRX0ZjbFJLaWZUSUk/view?usp=sharing)
> 告诉我，如果有任何麻烦，应尽快提供一些工具来进行预测和可视化。

hi, the link does not exist. That would be great if you could share pretrained models again. thank you so much.

**Comment by ICEAIyjp** [comment]
It would be great if you could share a pretrained model again,  please，the old website doesn't work.
