### ISSUE TITLE
about the pretrain model

### ISSUE THREAD

**Issue by ZhuohaoMai** [wbenbihi/hourglasstensorlfow#41]
why did the tiny pretrain model is bigger than the regular one, but used less conv layer?

**Comment by ZZM37** [comment]
Could you give me the pretrain model? The link is not available。。。If you can help me, please contact  me 1258662670@qq.com. Thank you very much!

**Comment by ZhuohaoMai** [comment]
> Could you give me the pretrain model? The link is not available。。。If you can help me, please contact me [1258662670@qq.com](mailto:1258662670@qq.com). Thank you very much!

maybe u need a vpn.

**Comment by ZZM37** [comment]
I have tried it, but it doesn't work.

**Comment by wuchenxi118** [comment]
@ZhuohaoMai I have vpn and I think the website is 404，could you share the pretrain model to help me save my time？Thanks!

**Comment by Wu-Jin-tao** [comment]
could you share the pretrain model to help me? please contact me 1359420292@qq.com. Thank you very much!

**Comment by ZhuohaoMai** [comment]
Sorry, I have graduated, all the data in the school server, I have been unable to take out.
