### ISSUE TITLE
Train generator used for computing the accuracy instead of valid generator

### ISSUE THREAD

**Issue by ayushgaud** [wbenbihi/hourglasstensorlfow#43]
Hi

I was going through the code and I found that `self.valid_gen` is defined but for accuracy prediction `self.generator` is being used here [L278](https://github.com/wbenbihi/hourglasstensorlfow/blob/master/hourglass_tiny.py#L278) which I think might be incorrect. Is it intentional?

Thanks

**Comment by mohaEs** [comment]
@ayushgaud have you correct that? I also need validation loss and accuracies. But val_gen brings errors.
