### ISSUE TITLE
Const used in hourglass_tiny.py

### ISSUE THREAD

**Issue by cloudy-toast** [wbenbihi/hourglasstensorlfow#46]
Hi Walid,

Thanks for sharing the code!
Could you please tell me why you used 91 in the function ' _compute_err(self, u, v)'?
I understand you want to calculate the distance btw two locations and rescale it to [0,1], but why not divide it by 64?

Best regards,
Ruobing

**Comment by thomas-liao** [comment]
91 is approximately  the maximum "error" in terms of euclidean distance in heat map you may get (i.e. prediction at [0, 0] while ground truth is [63, 63]

**Comment by weiyx16** [comment]
Yes, in fact 91 = 64*square(2). We need normalization here.
