### ISSUE TITLE
Process video footage

### ISSUE THREAD

**Issue by wbenbihi** [wbenbihi/hourglasstensorlfow#5]
Hi,

It is an issue regardig the PredictProcessor().videoProcessor() method.
predictClass.py line 564
`fourcc = cv2.VideoWriter_fourcc(*'DIVX') `
`outVid = cv2.VideoWriter( outName, fourcc, fps, tuple(shape.astype(np.int)), 1)`

I use this to open a video footage (*.mp4, *.avi), then process frames and save it in an other video file.
On windows, the code works fine except the output file is a video file of 6Ko. It does not save the frame with the `outVid.write(frame)` method.

Did anybody have a similar issue on OpenCV?

**Comment by bhack** [comment]
Can you very if a minimal camera capture writer is working with you setup? Just copy and run the videocapture example in [doc](http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html)

**Comment by wbenbihi** [comment]
I manage to solve this error.
If somebody had the same, you need to add opencv_ffmpeg_64.dll and opencv_ffmpeg.dll to the working directory.
Those files will be provided on the next commit.
