### ISSUE TITLE
Can you give a new website for the pretrained model?

### ISSUE THREAD

**Issue by yileichen123** [wbenbihi/hourglasstensorlfow#59]
The address in readme is none.

**Comment by PHaiJun** [comment]
I have the same problem and sent email to author, but without feedback.

**Comment by yyyyojiro** [comment]
> I have the same problem and sent email to author, but without feedback.

do you receive the author's reply? I also can't download the pretrained model from the disabled link.

**Comment by yileichen123** [comment]
已收到！
