### ISSUE TITLE
The link of pretrained model is not availbale？？？

### ISSUE THREAD

**Issue by TianshengSun** [wbenbihi/hourglasstensorlfow#63]
It seems like the link of pretrained model is not availbale. So , where can i find the pretrained model???

**Comment by Ziang-Wang** [comment]
> 似乎预训练模型的链接不可用。所以，我在哪里可以找到预训练模型？

hi, I have the same problem. Have you solved it?

**Comment by TianshengSun** [comment]
I 'm not solved yet, but you can choose another repo https://github.com/yuanyuanli85/Stacked_Hourglass_Network_Keras
